<?php
$CONFIG = array (
  'instanceid' => 'oc102ut20u76',
  'passwordsalt' => 'P31qUdhD1BZePixh6TMmpQiJn6CDWx',
  'secret' => 'CeOp6s4vSRIpra08ItL9rXNxWzhIotp1mJqv0Fq1HYTw6a9i',
  'trusted_domains' => 
  array (
    0 => '192.168.222.161',
  ),
  'datadirectory' => '/var/www/html/vanedisk/data',
  'overwrite.cli.url' => 'http://192.168.222.161/vanedisk',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'clouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'clouddbuser',
  'dbpassword' => 'Passw0rd',
  'logtimezone' => 'UTC',
  'installed' => true,
  'knowledgebaseenabled' => false,
  'appstoreenabled' => false,
  'default_language' => 'zh_CN',
  'mail_from_address' => 'zhukai',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'vanecloud.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp',
  'appstore.experimental.enabled' => false,
  'theme' => '',
  'preview_libreoffice_path' => '/usr/bin/libreoffice5.0',
);
